# https://developers.cloudflare.com/workers/wrangler/configuration
name = "hlog"
compatibility_date = "2021-06-11"

[assets]
directory = "./dist"
html_handling = "none"
not_found_handling = "404-page"
